### ISSUE TITLE
Plugin Id Conflit with Go Maven Task Plugin

### ISSUE THREAD

**Issue by shmc** [aresok/go-maven-poller#5]
When deploying Go Maven Nexus Plugin and Go Maven Task Plugin an error occurs due to the usage of the same plugin id.

Maybe the plugin might be change to maven-nexus?

2015-07-17 16:52:07,252  INFO [main] RailsAssetsService:66 - Found rails assets manifest file named manifest-99390a9420e28629ce0284d34cbefd47.json
2015-07-17 16:52:07,318  INFO [main] RailsAssetsService:70 - Successfully read rails assets manifest file located at /var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/rails.new/public/assets/manifest-99390a9420e28629ce0284d34cbefd47.json
2015-07-17 16:52:07,727  WARN [Thread-65] DefaultPluginJarLocationMonitor:321 - Plugin listener failed
java.lang.RuntimeException: Found another plugin with ID: maven
        at com.thoughtworks.go.plugin.infra.plugininfo.DefaultPluginRegistry.loadPlugin(DefaultPluginRegistry.java:41)
        at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.addPlugin(DefaultPluginJarChangeListener.java:108)
        at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.pluginJarAdded(DefaultPluginJarChangeListener.java:72)
        at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners$1.execute(DefaultPluginJarLocationMonitor.java:288)
        at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners.doOnAllPluginJarChangeListener(DefaultPluginJarLocationMonitor.java:319)
        at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners.pluginJarAdded(DefaultPluginJarLocationMonitor.java:286)
        at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.notifyListenersOfAddedPlugins(DefaultPluginJarLocationMonitor.java:210)
        at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.loadAndNotifyPluginsFrom(DefaultPluginJarLocationMonitor.java:198)
        at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.run(DefaultPluginJarLocationMonitor.java:184)

**Comment by christer79** [comment]
I also have this issue. 
+1 for fixing it
